services:
  mcp:
    container_name: ${MCP_CONTAINER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
        PORT: ${PORT}
    # image: ${MCP_IMAGE}   # 빌드 대신 사전 이미지 사용 시 주석 해제
    user: "${USER_ID}:${GROUP_ID}"
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      PORT: ${PORT}
      EXECUTOR_MODE: ${EXECUTOR_MODE}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_PREFIX: ${APP_PREFIX}
      SCOPES: ${SCOPES}
      MCP_TOKEN_FILE: ${MCP_TOKEN_FILE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "${HOST_SECRETS}:${SERVER_CTR_SECRETS}:ro"   # ./secrets -> /app/secrets (RO)
      - "./app:/app"
    restart: unless-stopped
