services:
  mcp:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${MCP_DOMAIN}`)"
      - "traefik.http.routers.${ROUTER_NAME}.entryPoints=${TRAEFIK_ENTRYPOINTS}"
      - "traefik.http.routers.${ROUTER_NAME}.tls=true"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=${ACME_RESOLVER}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
    networks:
      - traefik_ext

networks:
  traefik_ext:
    external: true
    name: ${TRAEFIK_NETWORK}
