version: "3.9"
services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=authentik
      - POSTGRES_USER=authentik
      - POSTGRES_DB=authentik
    volumes:
      - auth-pg:/var/lib/postgresql/data
  redis:
    image: docker.io/library/redis:7-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - auth-redis:/data
  server:
    image: ghcr.io/goauthentik/server:2024.8.2
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=authentik
      - AUTHENTIK_SECRET_KEY=please-change-me
    ports:
      - "${AUTHENTIK_HTTP_PORT:-9190}:9000" # http
      - "${AUTHENTIK_HTTPS_PORT:-9444}:9443" # https
    depends_on:
      - postgres
      - redis
  worker:
    image: ghcr.io/goauthentik/server:2024.8.2
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=authentik
      - AUTHENTIK_SECRET_KEY=please-change-me
    depends_on:
      - postgres
      - redis
volumes:
  auth-pg:
  auth-redis:
