version: '3.9'
services:
  mcp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp.rule=Host(`mcp-todo.example.com`)"
      - "traefik.http.routers.mcp.entryPoints=websecure"
      - "traefik.http.routers.mcp.tls.certresolver=lets-encrypt"
      - "traefik.http.services.mcp.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_public"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
