[project]
name = "mcp-ms-todo-server-auth-helper"
version = "0.1.0"
description = "Auth helper for MCP server (Azure CLI + MSAL)"
requires-python = ">=3.10,<3.13"
dependencies = [
    "msal>=1.33,<2.0",
    "PyJWT>=2.10,<3.0",
    "requests>=2.32,<3.0",
    "python-dotenv>=1.0,<2.0",
]
