name: CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest || echo "테스트 실패: 정책에 따라 알림 필요"
      - name: Docker build
        run: |
          docker build -t mcp-ms-todo-server .
      - name: Docker Compose up (테스트)
        run: |
          docker compose up -d
      - name: Clean up
        run: |
          docker compose down

  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.11.2
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL

